[build-system]
requires = [
    "setuptools>=82",
]

[project]
authors = [{ name = "op200" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
dependencies = [
    "maafw>=5.10.4",
    "music21>=10.1.0",
]
dynamic = ["version"]
license = "AGPL-3.0-or-later"
name = "ntetoolbox"
readme = "README.md"
requires-python = ">=3.14"

[project.urls]
Homepage = "https://github.com/op200/NTEToolbox"
Source   = "https://github.com/op200/NTEToolbox"

[project.optional-dependencies]
hearthstone = [
    "hslog>=1.19.0",
    "httpx>=0.27",
]

[tool.setuptools]
packages = ["agent", "hscoach"]

[tool.setuptools.dynamic]
version = { attr = "agent._version.__version__" }

[tool.setuptools.package-data]
ntetoolbox = ["assets/**/*"]
