name: check

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          cache: "pnpm"

      - name: Run maa-checker
        run: |
          pnpm i --frozen-lockfile
          npx @nekosu/maa-tools check

      - name: Install maafw
        run: |
          python -m pip install -U pip
          python -m pip install -U maafw
